earlephilhower/ESP8266Audio

src/AudioOutputI2S.cpp
if AudioOutputI2S is instanciated in a function (like in the examples) the member variables are not initialized to a default value.
=> initialize member variables

src/AudioFileSourceHTTPStream.cpp, src/AudioFileSourceICYStream.cpp
in ICYStream and HTTPStream:
swap readBytes(...) with read(...) which doesn't copy the bytes one by one.
This speeds up reading _considerably_ and makes streaming possible (in the first place) on the ESP32.
Seems to also work fine on ESP8266, but please somebody else check this.
=> make stream reads orders of magnitude faster (fixes #38)

src/AudioOutputI2S.cpp, src/AudioOutputI2S.h
enabling APLL seems to cause issues on multiple ESP32 boards. see issues #37 and #47.
a) make it user-configurable to allow the user to handle it for the specific board.
b) and revert to the old behavior and disable apll per default.
(this superseedes pull request #45)
=> handle esp32 apll issues

src/AudioFileSourceBuffer.cpp, src/AudioFileSourceBuffer.h
I'd like to draw the buffer fill level on a screen in order to debug streaming issues. unfortunately all of this is hidden inside the AudioFileSourceBuffer class. Can we make that accessible from outside?
=> report buffer fill level

src/AudioOutputI2S.cpp
as it is deprecated and changed behaviour between esp-idf v2.0 and v3.0. this fixes the chipmunks in #110 and #105 
please note that i2s_write_bytes() is also deprecated now. we should probably move to i2s_write() as mentioned in #105 but that isn't introduced until esp-idf v3.0 and not everybody might have that already.
=> replace esp32s i2s_push_sample()

src/AudioOutputI2S.cpp, src/AudioOutputI2S.h
The ESP32 has enough RAM to justify spending a bit more on the DMA buffer. So make the number of buffers configurable in the constructor.
This would allow us to spend more time in-between decoder->loop() calls. i.e. call it from an FreeRTOS task and do a longer vTaskDelay() (probably also in case of short decoding errors.)
WARNING: This changes the type signature of the constructor AudioOutputI2S. If you've previously called it with 3 arguments, this will break your code. Unfortunately this won't be at compile-time because both arguments are of the same type.
=> make dma_buf_count configurable by user, so we can have a larger dma buffer on ESP32

src/AudioFileSourceBuffer.cpp, src/AudioFileSourceBuffer.h
The ESP32 can easily handle a buffer size greater than UINT16_MAX (64KB)
so make the size an uint32_t.
=> increase max buffer size beyond 64k

src/AudioGeneratorFLAC.cpp, src/AudioGeneratorMIDI.cpp, src/AudioGeneratorMOD.cpp, src/AudioGeneratorMP3a.cpp, src/AudioGeneratorRTTTL.cpp, src/AudioGeneratorWAV.cpp
When using I2S on ESP32, i2s_zero_dma_buffer must be called when stopping playback to avoid hanging sound. This was implemented in AudioOutputI2S.cpp stop() method, but the call to this method from generators has only been added in the MP3 generator and not in other generator.
This PR adds a call to output->stop() in every generator stop() method except for MP3 generator which already had this call.
This PR fixes #149 
Best,
=> Call output->stop() when stopping generators

src/AudioFileSourceICYStream.cpp
beforeIcy can become 0 in:
https://github.com/earlephilhower/ESP8266Audio/blob/135e912f3ef435f763e4a68b2dc22da6d33ebc85/src/AudioFileSourceICYStream.cpp#L166
which causes a read of 0 bytes in the next line and subsequently makes ICYStream stop reading anything. this was the cause of the buffer underrun in #124 in the fist place.
unfortunately not easy to reproduce.
Also WiFiClient.read() can return -1 which messes with the length arithmetic. ~~I'll also add a commit for that.~~ ( https://github.com/espressif/arduino-esp32/blob/a0f0bd930cfd2d607bf3d3288f46e2d265dd2e11/libraries/WiFi/src/WiFiClient.cpp#L101 )
EDIT: And messing with the arithmetic might be the thing why it stops reading after that. So instead of merging this pull-request we could do the 0-bytes read and then:
`if (ret < 0) …
=> don't try to read 0 bytes if we hit the icy block (fixes #124)

README.md, examples/PlayMODFromPROGMEMToDAC/PlayMODFromPROGMEMToDAC.ino
I expected the internal DAC of ESP32 to be more clearly documented and to be included in the examples.
This PR adds some documentation to the Readme as well as a comment in example PlayMODFromPROGMEMToDAC.
As it seems to be a tradition: bravo et merci for this fantastic library!
=> Document the internal DAC on ESP32 more explicitly

src/libhelix-aac/assembly.h
ARDUINO #define defaults to PowerPC which is the wrong order for ESP32. Still, there might be a better #define to use rather than __XTSENSA__
=> AAC endianness

README.md, examples/PlayMP3ToSPDIF/PlayMP3ToSPDIF.ino, src/AudioOutputSPDIF.cpp, src/AudioOutputSPDIF.h
Added code adapted from Teensy Audio Library that outputs SPDIF encoded stream on I2S data pin. To interface with SPDIF receiver, you need optical or coaxial transceiver, for which some examples can be found at https://www.epanorama.net/documents/audio/spdif.html . 
The goal would be to output sound directly to SPDIF capable receiver without any external DAC, codec chips, etc... It works even with simplest form with red LED and current limiting resistor, fed into TOSLINK cable.
On ESP32 this seems to work well, if APLL is used, and almost any unused pin can be selected as output via `out = new AudioOutputSPDIF(<GPIO number>);`. Default output is GPIO27 and there is new example 'PlayMP3ToSPDIF' to demonstrate it.
On ESP8266, code seems to work, but your mileage may vary. Due to high bit …
=> Added S/PDIF output using I2S peripheral

README.md, examples/PlayFLAC-SD-SPDIF/PlayFLAC-SD-SPDIF.ino, examples/PlayMP3ToSPDIF/PlayMP3ToSPDIF.ino, keywords.txt, src/AudioGeneratorFLAC.cpp, src/AudioGeneratorFLAC.h, src/AudioOutputSPDIF.cpp, src/AudioOutputSPDIF.h, src/driver/SinglePinI2SDriver.cpp, src/driver/SinglePinI2SDriver.h, src/libflac/bitreader.c, src/libflac/format.c, src/libflac/stream_decoder.c
Added 
- SinglePinI2SDriver, ESP8266 minimal transmit-only rewrite of Arduino I2S driver specific for ESP8266Audio. Main feature is configurable size of DMA buffers
- Modified SPDIF output to use the minimal I2S driver
- FLAC decoder memory optimization on ESP8266
- FLAC playback from SD card example
- Misc. minor fixes
=> ESP8266 SinglePinI2SDriver, SPDIF output improvements, FLAC memory optimization

src/AudioOutputI2S.cpp, src/AudioOutputI2S.h, src/AudioOutputI2SNoDAC.cpp
The BCK and WS pins aren't needed or used when using the I2SNoDAC
option.  Restore their settings to whatever they were before, leaving
them untouched.  Apps may configure the additional pins either before or
after the I2SNoDac is created.
=> Free BCK and WS pins for general use with NoDAC

README.md, examples/StreamMP3FromHTTP_SPIRAM/StreamMP3FromHTTP_SPIRAM.ino, src/AudioFileSourceSPIRAMBuffer.cpp, src/AudioFileSourceSPIRAMBuffer.h, src/spiram-fast.h
Instead of requiring everyone to download and install another Arduino
library to use this lib, include an optimized, self-contained one from
the 8266 VM PR: https://github.com/esp8266/Arduino/pull/6994
Does change the API as it now requires a HW chip select, so that
parameter is removed from the SpiRAM buffer object.
=> Replace external SPIRAM lib w/internal optimized

src/AudioFileSourceSPIRAMBuffer.cpp, src/AudioFileSourceSPIRAMBuffer.h, src/spiram-fast.h
Seems like VSCODE and others try and compile all files in a directory,
even if they aren't used.  Because the spiram-fast had ESP8266-only
registers, it caused an error when attempting to build anything for the
ESP32.
Update by writing a new SPI class based version of the spiram-fast class
(tested on the ESP8266) which uses the SPI wrapper class.
Fixes #253
@Maigre, can you give this a test and make sure it fixes the issue?  Thx!
=> Fix ESP32 compilation, add SPI class RAM wrapper

src/libflac/stream_decoder.c
I just moved the #endif to where it was in the previous version I was using.
=> Fix compilation error in new libflac/stream_decoder

src/AudioGeneratorMP3.cpp, src/AudioGeneratorMP3.h
Keep track of how many values are actually good in the buffer (before it
was always guaranteed to be the full size) and when EOF is detected,
only shift out valid, good bytes, and return STOP when the unused bytes
are 0 or unchanged from the last pass.
Fixes #265
=> Redo the last packet handling of the MP3 decoder

src/AudioOutput.h, src/AudioOutputI2S.cpp, src/AudioOutputI2S.h
Thanks to @ikostoski tipps I created my first C++ PR :-)
* added `flush()` to `AudioOutput.h`
* implemented the described DMA consume loop
* tested it with my sample project (worked like a charm)
I did not add the call `flush()` to the `stop()` method, because sometimes you just want to stop ;-). In other words: You have to call explicitly `flush()` in order to push out the last wave bits in to the DAC.
=> added missing DMA buffer flush, see issue #270 for details

src/AudioFileSourceHTTPStream.cpp
This helps when true urls are behind redirects. Tested with:
```http://stream.rcs.revma.com/ypqt40u0x1zuv```
also automatically deleted a trailing space :)
=> Follow redirects

src/AudioGeneratorMIDI.cpp
Velocity in the MIDI format goes from 1...127, so scale the voulme of
the note generater by /128 instead of /256.   Increases volume of all
notes by 2x linratly (3dB).
Found by Marc Madaule
=> Fix factor-of-2-off MIDI velocity parsing

src/libtinysoundfont/tsf.h
Patch 21c07c0bcd702e7adf3db349ac926914b98d17ce was applied to the TSF's
original code, but not to the fixed-point generator used by the ESP8266.
Apply it to the FP unit as well.
Spotted by Marc Madaule
=> Fix missed merge in MIDI notegen

src/AudioGeneratorAAC.cpp
As noted by Marc Madaule (thanks!), the mono AAC decode was not
functioning properly.  Adjust the output stuff loop to fix.
=> Fix AAC mono decode

src/libtinysoundfont/tsf.h
There are 2 problems with `tsf_stream_memory`:
1. a small one, is that `skip` doesn't actually behave like the file version
2. a big one, in the "segfault" sense, is that the `tsf_stream_memory` struct created inside `tsf_load_memory` does not survive that function, but `t->hydra->stream` will keep a reference to it for delayed loading
This patch fixes both those problems. With this, I successfully built and ran tsf in a ESP32 with a soundfound linked in PROGMEM.
=> fix memory loading

examples/StreamOnHost/StreamOnHost.ino, examples/StreamOnHost/onHost, src/AudioGeneratorMP3.cpp
Debugging helper by executing on host.
(it needs latest esp8266 arduino master)
=> test/run on host, output to null device

src/AudioGenerator.h, src/AudioGeneratorMP3.cpp, src/AudioGeneratorMP3.h
This PR:
- add desync() for user to call when randomly seeking in the input file
- try to fix corner cases leading to exceptions when seeking (`memmove(size=-1)`)
This PR also adds a new constructor for preallocated structures, intended to be tried with IRAM memory area.
That part can be pulled out and made into another PR.
=> Fixes when seeking in an MP3 file

library.json
PlatformIO requires these dependencies to be explicitly mentioned. Please check the version numbers of the libraries specified are correct. However, v1.0 for each allows for successful builds. Thanks!
=> Fix the dependencies in the library's PIO config

src/AudioGeneratorMP3.cpp
When reusing the AudioGeneratorMP3 object to play multiple files with errors, the error count was never reset.
Also, if 3 errors are encountered, it would stop running but never clean up the buffers.
=> Reset errors and avoid memory leak

src/AudioOutputULP.cpp, src/AudioOutputULP.h
Code courtesy of Martin Laclaustra.
Uses the ULP coprocessor on the ESP32 to send samples to the onboard
DACs, freeing the I2S port for other uses.
Connect left output to pin 25, right to pin 26.
=> Add output via the ULP for the ESP32

src/AudioOutputI2S.cpp, src/AudioOutputI2S.h
Moved most of the constructor login into the begin method except for setting up variables/defaults. Now when you set any variables before calling begin it stores those variables until begin is called which sets i2sOn to true. Then those methods work like they previously did.
Addressing Issues: #330
=> Modify AudioOutputI2S to initialize i2s during begin

src/AudioFileSourceFS.h, src/AudioFileSourceID3.cpp
I've run into a problem while parsing tags in mp3 files with embedded images (`APIC` frames), with my program freezing.
It appears that the `for loop` which populate the `value` buffer has an `int16_t` as a counter, thus overflowing when frame size is above 65535 bytes. I've changed it to an `int32_t`.
Besides, I needed some other tags to be extracted for my projects, I've thus added the following ones : 
`TRCK / TRK`track number (+ total tracks)
`TPOS / TPA` part of a set (+ total set) _i.e._ if the album has several discs.
`POPM / POP` popularimeter, _aka_ rating.
`TCMP` "part of a compilation". It's not clear if this one is an off-standard added by iTunes, or if it's included in ID3v4
=> tags framesize endless loop

src/AudioOutputULP.cpp, src/AudioOutputULP.h
Fixes for the ULP driver:
- Fix the order of mono samples (each pair was swapped)
- Remove comment on version and date (currently tracked within ESP8266Audio repo)
- Added some usage instructions to the header file
- Delete sample in buffer after being rendered (ULP) to avoid sound looping in the buffer at the end of playback
=> Fixes for the ULP driver

src/AudioOutputI2S.cpp, src/AudioOutputI2S.h, src/AudioOutputI2SNoDAC.h
Conflicts with repurposed GPIO, found when using SPI SS GPIO (using SDFS), are avoided.
Related: https://github.com/esp8266/Arduino/pull/7748
=> Fix for esp8266 I2S/NoDAC

src/AudioFileSourceICYStream.cpp
Thanks to @cjwhoishe, fixes #355 .
When a large enough read size was requested it is possible that for some
streams multiple ICY blocks could appear.  The logic doesn't support
that, so only read up to 1/2 the ICY block interval to ensure there is
no way to see two ICY blocks in one readInternal call.
=> Ensure only 1 ICY packet processed per reading

examples/StreamMP3FromHTTP/StreamMP3FromHTTP.ino, examples/StreamOnHost/AudioOutputNullSlow.h, examples/StreamOnHost/StreamOnHost.ino, examples/StreamOnHost/onHost, src/AudioFileSourceHTTPStream.cpp, src/AudioFileSourceICYStream.cpp
- In the ICY recent fix, add a check for `icyMetaInt` that has been seen to be 0
- Two short buffer size (seen by compiler when using emulation on host)
- `StreamOnHost` example:
- Make it slower so it can reveal some issue with some URL
- Make it look like better with the real HTTP example
- Always show cmdline help in the `./onHost` script
=> Proposal for various tiny fixes

src/AudioOutputFilterBiquad.cpp, src/AudioOutputFilterBiquad.h
Based off the work of Nigel Redmon (http://www.earlevel.com/main/2012/11/26/biquad-c-source-code/), seems to work A1 with my setup, though it might need some polishing to lower the resources needed for operation. I am currently dividing by two the input sample value to avoid any clipping, but I'm looking for a cleaner solution to this as well!
I have a webradio player build around TFT_eSPI, an ST7735 (128x160 LCD), a rotary encoder and a WeMos D1 Mini for testing, and it crashes after I add a second Biquad filter in the audio pipeline. Is this CPU or RAM-related, that's what I am wondering!
=> Working implementation of a Biquad filter for the fixed-point CPU of the ESP8266

examples/PlayWAVFromPROGMEM/PlayWAVFromPROGMEM.ino
Remove unused WiFi library from `PlayWAVFromPROGMEM.ino` to reduce the storage capacity. Found on esp32 v1.0.6 on Arduino IDE.
> Sketch uses 1332662 bytes (101%) of program storage space. Maximum is 1310720 bytes.
> Global variables use 38648 bytes (11%) of dynamic memory, leaving 289032 bytes for local variables. Maximum is 327680 bytes.
> text section exceeds available space in board
> Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
> Error compiling for board ESP32 Dev Module.
=> Fix compile error due to insufficient capacity

src/AudioFileSourceFunction.cpp
Sorry, in the first call of `funcs[0](time)`, `time` should be zero but it was not...
=> Fix the start of the arg “time” is not zero

src/AudioOutputI2S.cpp, src/AudioOutputI2SNoDAC.cpp
Fix I2S on esp8266 Arduino core v>=3
I believe this change is backward compatible with older versions as well.
fixes #398
=> i2s on esp8266: fix include

src/AudioFileSourceLittleFS.h
Now ESP32 Arduino 2.0.0 has LittleFS available.
I tested that this change works: mp3 plays fine from LittleFS.
=> Make LittleFS file source available for ESP32

examples/PlayMIDIFromSPIFFS/PlayMIDIFromSPIFFS.ino
Without this fix, there is no sound and the serial monitor shows:
```
Starting up...
[E][vfs_api.cpp:22] open(): File system is not mounted
[E][vfs_api.cpp:22] open(): File system is not mounted
BEGIN...
MIDI done
MIDI done
```
After this fix there is sound and no error on the serial monitor.
The change is similar to the code in https://github.com/earlephilhower/ESP8266Audio/blob/master/examples/PlayMP3FromSPIFFS/PlayMP3FromSPIFFS.ino
=> Fix: add missing SPIFFS.begin()

src/AudioOutputI2S.cpp, src/AudioOutputI2SNoDAC.cpp
Recent releases of ESP8266Audio doesn't compile (on Linux) with ESP8266 Arduino versions before 3.0.0. This is due to i2s.h being changed to upper case.
This PR considers the version of Arduino to include the right header file.
=> Fixing I2S includes to work with ESP8266 Arduino version < 3.0.0

src/AudioFileSourceSPIRAMBuffer.cpp, src/AudioOutputI2S.cpp, src/AudioOutputSPDIF.cpp, src/AudioOutputULP.cpp
To be able to compile the library on ESP32-C3, some little changes were necessary:
- ESP32-C3 has no ULP co-processor
- uint32_t and size_t are not identical on RISC-V
- ESP32-C3 has no builtin DAC
This fixes issue https://github.com/earlephilhower/ESP8266Audio/issues/442
=> ESP32-C3 Support

src/AudioOutputI2S.cpp, src/AudioOutputI2S.h
Some DACs don't support I2S but are perfectly capable of playing audio. This PR adds a method to set AudioOutputI2S from I2S to LSB Justified mode. Unfortunately the naming of constants in ESP32 SDK is far from perfect and it's inconsistent between ESP-IDF releases. 
ESP8266 SDK always sets I2S mode in i2s_rxtx_begin() so apparently there's no way to configure it. No idea how RP2040 handles that. If you'd like me to put the new code inside #ifdef ESP32, please let me know.
=> Support LSB Justified DACs on ESP32 (e.g. PT8211)

src/AudioOutputI2S.cpp, src/AudioOutputSPDIF.cpp
The PR to make the library compatible with ESP32C3 was not fully correct: Builtin DAC&PDM functionality was lost on ESP32. This should fix it again.
Also some compiling warnings are removed about I2S_COMM_FORMAT_STAND_MSB being deprecated, when compiling in the ESP32 Arduino core v2 (IDF>=4.2)
https://github.com/earlephilhower/ESP8266Audio/issues/442
=> I2S Fix Builtin DAC&PDM on ESP32 & compiling warning ESP32-C3

src/libhelix-aac/assembly.h
The library produces white noise when playing AAC streams because of a little/big endian issue.
=> AAC playback on RISC-V processor (ESP32C3)

src/AudioOutputI2S.cpp
Increase I2S buffer size from 64 samples/ block to 128 samples/block on ESP32/ESP32C3. 
This fixes sound artefacts described in issue https://github.com/earlephilhower/ESP8266Audio/issues/442
=> Increase I2S buffer size

src/AudioGeneratorRTTTL.cpp
This fixes the issue that the PlayRTTTLToI2SDAC example doesn't stop at the end of the song. It has been reported twice:
- https://github.com/earlephilhower/ESP8266Audio/issues/327
- https://github.com/earlephilhower/ESP8266Audio/issues/471
The cause of the problem is the variable `running` which is set to false when the last note has been played. As a result
`output->stop()` is not called.
This should fix it. I think it needs a check to be sure that` output`/`file` is not NULL, but I am not sure on the return value true/false.
=> Fix RTTTL stop on ESP32

src/AudioGeneratorMOD.cpp, src/AudioOutputI2S.cpp
This PR is my proposed fix for issue #474:
* fix a tricky small bug in AudioGeneratorMOD::ProcessRow, that causes incorrect treatment of a specific effect modifier.
* abort playback when more than the configured channels are required.
* fix int16 overflow in AudioGeneratorMOD::GetSample
* make AudioGeneratorMOD::GetSample deliver output in int16 (signed) format
* added saturation logic, to avoid random noise in case of over-amplification
* AudioOutputI2S.cpp internalDAC: made sample conversion to uint16 a bit safer
I'm currently working on another PR, to use the full 16bit range of output in AudioGeneratorMOD::GetSample, including preserving a few more "real" bits of accuracy that currently get lost during up-sampling, down-shifting and mixing steps.
This will also include some debugging …
=> fix for issue #474, and a few other bugs in MODGenerator

src/AudioGeneratorMOD.cpp, src/AudioGeneratorMOD.h
Hi,
This is a follow-on to my previous PR. I did a few tweaks that improve the "real" resolution (from 10bit to 12-14bit).
I have also enabled 8-channel playback, however this means that many internal structures are now 2x the size - please check if this is OK from memory usage perspective.
I only have internalDAC so I could not check if its an audible improvement. However I verified that the wavform (WAV file output) looks similar (see attached picture). If you look closely at the frequency (spectral) plot, you may notice that there is less "blue noise" in the higher frequencies, as consequence of the more accurate interpolation of instrument samples.
=> AudiogeneratorMOD: use full 16bit with slightly better accuracy

src/AudioOutputI2SNoDAC.cpp, src/AudioOutputI2SNoDAC.h
The AudioOutputI2SNoDAC was passing port to the sampleRate and false as the sck to the parent constructor of AudioOutputI2S.  The AudioOutputI2S has an alternate constructor for the RP2040, the the AudioOutputI2SNoDAC had not been updated to pass the values correctly to the parent class using the alternate constructor for the RP2040.
=> AudioOutputI2SNoDAC not working for RP2040 due to constructor differences with AudioOutputI2S (parent class)

src/AudioGeneratorMOD.cpp
small oops in my previous PR - output->flush was not called after normal "end of song".
=> small fix - flush after normal end of playback

library.json, library.properties
When creating a PlatformIO project referencing this library with the default options
```ini
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = earlephilhower/ESP8266Audio@^1.9.5
```
A simple sketch with
```cpp
#include <Arduino.h>
#include "AudioGeneratorAAC.h"
#include "AudioOutputI2S.h"
#include "AudioFileSourcePROGMEM.h"
void setup() {}
void loop() {}
```
fails to compile with not finding `ESP8266HTTPClient.h`. This is because this library uses `#ifdef` checks to check for the target architecture, but PlatformIO's [library dependency finder search mode](https://docs.platformio.org/en/latest/librarymanager/ldf.html#dependency-finder-mode) does not evaluate these checks, and finds none of the dependencies of this library, hence failing the build. …
=> Fix PlatformIO library search mode

src/AudioFileSourceFunction.cpp, src/AudioOutputI2S.cpp, src/AudioOutputI2S.h, src/AudioOutputI2SNoDAC.cpp, src/AudioOutputSPIFFSWAV.cpp, src/AudioOutputSPIFFSWAV.h, tests/common.sh
The I2S subsystem was rewritten in the RP2040 core V2.0, so update to
use the new object and calls.
Also clean up some code warnings and remove SPIFFS from the RP2040
=> Update for RP2040 core v2.0 new I2S

tests/common.sh
The ESP32 coffee now builds without warnings, so at Werror back
=> Enable Werror for ESP32

src/libtinysoundfont/tsf.h
By playing some midi files I noticed some notes were being randomly distorted. The cause was not using the fixed point value for `tmpLoopStart` for positioning `tmpSourceSamplePositionF32P32`
=> fixed: tmpSourceSamplePositionF32P32 jumping to incorrect position causing distorted sound

src/AudioOutputI2S.cpp, src/AudioOutputSPDIF.cpp
The last contribution broke compilation on IDF <4.4.0. This is a problem as the library now no longer compiles on ESP32 core 1.0.6, the most stable version.
AudioOutputI2S.cpp & AudioOutputSPDIF.cpp do'n't compile because of unknown mck_io_num, mclk_multiple, bits_per_chan, I2S_MCLK_MULTIPLE_DEFAULT and I2S_BITS_PER_CHAN_DEFAULT.
This PR fixes the compilation problem.
=> ESP32: Fix compilation of I2S in Arduino ESP32 core 1.0.6

examples/PlayMIDIFromSPIFFS/PlayMIDIFromSPIFFS.ino, src/AudioGeneratorMIDI.cpp, src/AudioGeneratorMIDI.h
See: https://github.com/earlephilhower/ESP8266Audio/pull/502
Tested on `toolchain-riscv32-esp @ 8.4.0+2021r2-patch3`
=> Fix build support gcc8 for other arch

src/AudioOutputI2S.cpp
* ESP32: When calling the destructor of AudioOutputI2S after having called the stop function, followed by creating of a new AudioOutputI2S object,  an error is shown "I2S: register I2S object to platform failed" in IDF 4.4.
This is because i2s_driver_uninstall had not been called in the destructor because i2sOn was already set to false in the function stop. 
It is necessary to call i2s_driver_uninstall before i2s_driver_install is being called again in the begin function. That is why I moved it to the stop function
* ESP8266 : the same problem with i2s_end not being called called when calling the stop function followed by the destructor bacause i2sOn is set to false in the stop function.
This results in new call to i2s_rxtx_begin without first having called i2s_end.
My idea is that also …
=> AudioOutputI2S  : error "I2S: register I2S object to platform failed" : destructor & stop

src/AudioGeneratorMP3.cpp
Hello, Thanks for this great library and your work !
I have noticed that when I play a mono MP3, the right channel contains a buzzing sound.
https://user-images.githubusercontent.com/42724151/181280976-96016bac-9fe4-4213-b666-2deb13ee0616.MOV
On the other hand, the AAC decoder appears to assign the same data to both channels from mono data.
So, in this pull request, I copied the data from the left channel to the right channel when the data is mono, so that the buzzer-like sound is not output.
I just couldn't decide if it would be best to make the change at this location in the source code.
If you like this modification, I would be happy to hear from you, but if you have any suggestions on where I should fix it, please direct me.
Best regards.
=> fix: Invalid data is assigned to the right channel when playing a mono MP3.

src/AudioOutputI2S.cpp, src/AudioOutputI2S.h
This PR partially fixes [Issue 638](https://github.com/earlephilhower/ESP8266Audio/issues/638)
It only implements the logic for rp2040, as I do not have the other boards, but it should be similar to do.
=> Add ability to SwapClocks(bool) on I2S. RP2040 only. Partially fixes #638

tests/common.sh
ESP32 Arduino has changed their test infrastructure, need to adjust
=> Get ESP32 CI builds working again

src/AudioGeneratorRTTTL.cpp
According to RTTTL spec:
https://www.mobilefish.com/tutorials/rtttl/rtttl_quickguide_specification.html
> A dotted character (.) can be specified AFTER the duration-pitch-octave pair.
Before this change the note like `a4.` cannot be parsed and the tone ends.
=> RTTTL: parse dot after octave

src/AudioGeneratorMP3.cpp
AudioGeneratorMP3 starts its output, but if OOM during begin(), never stops its output.
This leads to downstream issues, including mixer not processing audio from the dead stub or any active ones.
=> AudioGeneratorMP3::begin - Stop output on OOM

examples/PlayMIDIFromSPIFFS/PlayMIDIFromSPIFFS.ino, src/AudioFileSourceHTTPStream.cpp, src/AudioFileSourceHTTPStream.h, src/AudioFileSourceICYStream.cpp, src/AudioGeneratorMIDI.cpp, src/AudioGeneratorMIDI.h, src/AudioOutputI2S.cpp, src/AudioOutputSPDIF.cpp, src/libhelix-mp3/mpadecobjfixpt.h, src/libtinysoundfont/tsf.h
Implement the renamed network client and other API changes when built under the 3.x branch of the Arduino ESP32 core.
Disable building TSF on the ESP32, the Xtensa G++ backend bug is still there.
Minimal changes to get I2S to build under new IDF.  Deprecated but not removed, so warnings are expected but should not be fatal in use.
Fixes #683
=> Update for ESP32 Arduino 3.x

src/AudioOutputMixer.cpp, src/libhelix-aac/decelmnt.c, src/libhelix-aac/noiseless.c, src/libhelix-aac/sbrside.c
* Ensure AAC read-in doesn't overflow internal structures when the file is corrupted/illegal.
* Fix pedantic GCC14 warnings on calloc order
=> Fix GCC14-detected warnings

src/AudioOutputPWM.cpp
Hej Earle,  
This PR adds PWMAudio to initializer list, which allows changing output pin per constructor.
Furthermore I added amplification.
There is a defaults-mismatch/-ambiguity regarding mono/stereo. I might take a look into it but that most likely requires some discussion..
=> AudioOutputPWM: fixed constructor for custom out-pin, added amplification

src/libtinysoundfont/tsf.h
=> Only block tsf.h on Xtensa ESP32, not RISCV

src/libmad/layer3.c
This should fix the crash of issue #704 on ESP8266 on recent versions.  At least it fixed it for my application.
=> Fixing crash on MP3 playback on ESP8266.

src/libhelix-aac/aacdec.h, src/libhelix-aac/assembly.h
The [Thingino open source camera project](https://thingino.com) would like to use ESP8266Audio for AAC decoding. The Ingenic cameras use the MIPS CPU architecture and this patch gets the project to compile.
=> Add support for MIPS CPU architecture

src/libhelix-aac/fft.c, src/libhelix-aac/huffmanaac.c, src/libhelix-aac/sbr.h, src/libhelix-aac/sbrhuff.c, src/libhelix-aac/sbrtabs.c, src/libhelix-aac/trigtabs.c, tests/host/Makefile
Import the optimized (well...de-un-optimized) version of libhelix from BackgroundAudio for about a 20% speedup on the Pico for AAC decode.
=> Speed up AAC decode by ~20% on Pico/ESP32

src/AudioOutputInternalDAC.h
- Tested working on esp32 and esp32-s2.
- Mono And Stereo both work, but there is a bug in ESP-IDF espressif/esp-idf#11425 . Until that is fixed in upstream, stereo mode is effectively useless.
- Note: If using stereo mode on esp32-s2, remove the physical pullup resistor from pin 18.
=> added internal DAC support via DMA

examples/MixerSample/MixerSample.ino, examples/PlayAACFromPROGMEM/PlayAACFromPROGMEM.ino, examples/PlayFLACFromPROGMEMToDAC/PlayFLACFromPROGMEMToDAC.ino, examples/PlayMIDIFromLittleFS/PlayMIDIFromLittleFS.ino, examples/PlayMODFromPROGMEMToDAC/PlayMODFromPROGMEMToDAC.ino, examples/TalkingClockI2S/TalkingClockI2S.ino, examples/WebRadio/WebRadio.ino, examples/WebRadio/web.cpp, src/AudioFileSource.h, src/AudioFileSourceHTTPStream.cpp, src/AudioFileSourceHTTPStream.h, src/AudioFileSourceICYStream.cpp, src/AudioFileSourceICYStream.h, src/AudioGeneratorMP3.cpp, src/AudioOutputPWM.cpp, tests/build-ci.sh, tests/common.sh
MP3 comes in chunks of encoded data started by a header sequence. Scan for it in the decoder and only pass in data that starts with this header to avoid the burst errors
Avoids a avalance of `lost synchronization` error reports when there is a file error.
Also enable some of the web sources on the RP2040/RP2350
=> Scan MP3 for header, avoid multiple burst errors

src/libtinysoundfont/tsf.h
Potential fix for [https://github.com/earlephilhower/ESP8266Audio/security/code-scanning/9](https://github.com/earlephilhower/ESP8266Audio/security/code-scanning/9)
To fix the issue, the array access should only happen after confirming that the index is valid. Specifically, change the condition in line 1874 from
```c
if (f->presets[preset].regions == NULL && preset >= 0 && preset < f->presetNum)
```
to
```c
if (preset >= 0 && preset < f->presetNum && f->presets[preset].regions == NULL)
```
This ensures that no matter what value `preset` has, `f->presets[preset]` is only accessed after confirming it's within range.
Edit only the conditional in `tsf_get_presetname` as shown above. No new methods or imports are required.
---
_Suggested fixes powered by Copilot Autofix. Review carefully …
=> Potential fix for code scanning alert no. 9: Array offset used before range check
