- src/AudioOutputI2S.cpp
> don't use audio pll on buggy rev0 chips

- src/AudioGeneratorWAV.cpp
Modified ReadWAVInfo method to give meaningful messages to Serial when…… it cannot read a WAV file, and also added code to handle WAV files that contain JUNK data, which is a valid part of the WAV specification.
> Added failure messages to ReadWAVInfo, also handled JUNK in WAV 

- src/AudioFileSourceBuffer.cpp
- src/AudioFileSourceHTTPStream.cpp
- src/AudioGeneratorWAV.cpp
Fixes: #223
* add basic seek() in Buffer that works with HTTPStream
* add error message in ReadWAVInfo() if seek() fails
* add error message in HTTPStream if seek() is called
> Allow playing wav files via HTTPStream

- src/driver/SinglePinI2SDriver.cpp
- src/driver/SinglePinI2SDriver.h
> Fix compile error on ESP32

- src/libtinysoundfont/tsf.h
LibTinySoundFont has been modified significantly since I forked
it to do the ESP8266 edits.  Update to latest merges.
Tested using the LittleFS MIDI example and seems to work well.
> Update to latest TinySoundFont

- README.md
I'm not as active as I'd like to be with this, so add a gitter channel
and allow folks to collaborate amongst themselves on technical questions
or projects.
> Add gitter.im channel to README

- src/AudioFileSourceFATFS.h
Thanks to Marc Madaule for the patch adding FatFS for the ESP32 as a
file source.
> Add FatFS file source

- library.json
- library.properties
Bugfixes to AAC and Opus codec addition
> Release 1.5.1

- tests/common.sh
Thanks to @d-a-v for the debug!
> Work around Arduino-Builder bug causing ESP8266 build fail

- examples/StreamOnHost/AudioOutputLinuxDSP.h
- examples/StreamOnHost/AudioOutputNullSlow.h
- examples/StreamOnHost/StreamOnHost.ino
- examples/StreamOnHost/onHost
This little addition may help debugging with some streams
> StreamOnHost: play audio on host

- tests/common.sh
Reverts earlephilhower/ESP8266Audio#358
Arduino-CLI has fixed a bug in their code, attempt to run nightly builds in CI again.
> Revert "Work around Arduino-Builder bug causing ESP8266 build fail"

- examples/PlayWAVFromFunction/PlayWAVFromFunction.ino
- src/AudioFileSourceFunction.cpp
- src/AudioFileSourceFunction.h
Hi @earlephilhower , thank you for this great audio library. I've made some extension named `AudioFileSourceFunction`  that can easily play "raw" audio like sine wave which is generated by functions which has 1 float argument(time) and 1 float return(amplitude). 
```C++
// AudioFileSourceFunction can generate sound from function
file = new AudioFileSourceFunction(8.); // [sec]
file->addAudioGenerators([](const float time) {
return sin(TWO_PI * 440.f * time);  // C
});
// same as other examples
out = new AudioOutputI2SNoDAC();
wav = new AudioGeneratorWAV();
wav->begin(file, out)
```
`AudioFileSourceFunction` generates the WAV file header and its audio data will be generated each time based on the registered function when requested.
```C++
file = new AudioFileSourceFunction(sec, channels, …
```
> Proposal to add `AudioFileSourceFunction` which can generate sound from functions

- src/AudioOutputI2S.cpp
- src/AudioOutputI2SNoDAC.cpp
It can be compiled successfully and functionally tested without problems.
> Fix 'i2s_write_bytes' was not declared in this scope

- examples/StreamMP3FromHTTPToSPDIF/StreamMP3FromHTTPToSPDIF.ino
Stream MP3 from HTTP to SPDIF
Tested with:
ESP8266 NodeMCU connecting LED to pin RX and GND
URLs:
mp3 radio streams
Logitech Media Server stream from Raspberry Pi3
Removed all callbacks as there were issues with some radios and Logitech Media Server stream
Current solution is stable and working for hours.
> Stream MP3 from HTTP to SPDIF

- src/AudioGeneratorMOD.cpp
- src/AudioGeneratorMOD.h
- src/AudioOutputSTDIO.cpp
- tests/host/Makefile
- tests/host/mod.cpp
> Add MOD test, update DIVIDER name

- src/AudioOutputI2SNoDAC.h
> Fix overflow with x256 oversampling in I2SNoDAC

- tests/common.sh
sketch_utils.sh now requires to put flag names and this is breaking current build process
> fix: esp32 build process

- src/AudioOutputI2S.cpp
This allows us to use the Waveshare Pico Audio board with ESP8266Audio
> Add MCLK support for RP2040

- src/AudioGeneratorMP3.cpp
Fixes #715.  Good catch, @EternityForest
> Ensure MP3 can safely exit on OOM

- tests/common.sh
No idea how it started failing, the 8266 repo is dead and shouldn't be changing...
> Bring back ESP8266 Arduino CI
